version: '3'

services:
  nsupdate:
    image: git.debilux.org/chris/nsupdate
    container_name: nsupdate
    environment:
      - SCHEDULE="*\2 * * * *"
      - TZ=Europe/Berlin
      - NSUPDATE_INWX_USER=YOUR_INWX_USERNAME
      - NSUPDATE_INWX_PASSWORD=YOUR_INWX_PASSWORD
    volumes:
      - ./data:/config
      - ./log:/log
    restart: unless-stopped