services:
  nsupdate:
    image: git.debilux.org/chris/nsupdate:latest
    container_name: nsupdate
    restart: unless-stopped
    environment:
      - PUID=1000 # (default: 1000)
      - PGID=1000 # (default: 1000)
      - VERBOSE=false
      - DEBUG=false
      - SCHEDULE=*/2 * * * * (default: * * * * *)
      - TZ=Europe/Berlin # (default: Etc/UTC)
      - NSUPDATE_INWX_USER=${NSUPDATE_INWX_USER}
      - NSUPDATE_INWX_PASSWORD=${NSUPDATE_INWX_PASSWORD}
    volumes:
      - ./config:/config
      - ./log:/log